// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Depoimento documents
 */
interface DepoimentosDocumentData {
  /**
   * Texto Depoimento field in *Depoimento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.texto_depoimento
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto_depoimento: prismic.KeyTextField;

  /**
   * Nome Autor field in *Depoimento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.nome_autor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_autor: prismic.KeyTextField;

  /**
   * Função field in *Depoimento*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.funcao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  funcao: prismic.KeyTextField;

  /**
   * Avatar field in *Depoimento*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;
}

/**
 * Depoimento document from Prismic
 *
 * - **API ID**: `depoimentos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DepoimentosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DepoimentosDocumentData>,
    "depoimentos",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | FuncionalidadesSlice
  | ConteudoSlice
  | CallToActionSlice
  | DepoimentosSlice
  | HeroSectionSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | FormSlice
  | HeroSectionSlice
  | ConteudoSlice
  | CallToActionSlice
  | DepoimentosSlice
  | FuncionalidadesSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navegação*
 */
export interface SettingsDocumentDataNavegacaoItem {
  /**
   * Link field in *Settings → Navegação*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navegacao[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Keywords field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never> /**
   * Navegação field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navegacao[]
   * - **Tab**: Navegação
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  navegacao: prismic.GroupField<Simplify<SettingsDocumentDataNavegacaoItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | DepoimentosDocument
  | HomeDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Titulo Call To Action field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.titulo_call_to_action
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo_call_to_action: prismic.TitleField;

  /**
   * Descricao Call To Action field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.descricao_call_to_action
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_call_to_action: prismic.KeyTextField;

  /**
   * Link CTA field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.link_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *Conteudo → Default → Primary*
 */
export interface ConteudoSliceDefaultPrimary {
  /**
   * Texto Seção field in *Conteudo → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: conteudo.default.primary.texto_secao
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_secao: prismic.TitleField;

  /**
   * Descrição Seção field in *Conteudo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conteudo.default.primary.descricao_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_secao: prismic.KeyTextField;

  /**
   * Imagem Seção field in *Conteudo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: conteudo.default.primary.imagem_secao
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_secao: prismic.ImageField<never>;
}

/**
 * Default variation for Conteudo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConteudoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConteudoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Conteudo → Imagem Direita → Primary*
 */
export interface ConteudoSliceImagemDireitaPrimary {
  /**
   * Texto Seção field in *Conteudo → Imagem Direita → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: conteudo.imagemDireita.primary.texto_secao
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_secao: prismic.TitleField;

  /**
   * Descrição Seção field in *Conteudo → Imagem Direita → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conteudo.imagemDireita.primary.descricao_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_secao: prismic.KeyTextField;

  /**
   * Imagem Seção field in *Conteudo → Imagem Direita → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: conteudo.imagemDireita.primary.imagem_secao
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_secao: prismic.ImageField<never>;
}

/**
 * Imagem Direita variation for Conteudo Slice
 *
 * - **API ID**: `imagemDireita`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConteudoSliceImagemDireita = prismic.SharedSliceVariation<
  "imagemDireita",
  Simplify<ConteudoSliceImagemDireitaPrimary>,
  never
>;

/**
 * Slice variation for *Conteudo*
 */
type ConteudoSliceVariation = ConteudoSliceDefault | ConteudoSliceImagemDireita;

/**
 * Conteudo Shared Slice
 *
 * - **API ID**: `conteudo`
 * - **Description**: Conteudo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConteudoSlice = prismic.SharedSlice<
  "conteudo",
  ConteudoSliceVariation
>;

/**
 * Item in *Depoimentos → Default → Primary → Depoimentos*
 */
export interface DepoimentosSliceDefaultPrimaryDepoimentosFetchItem {
  /**
   * Card Depoimentos field in *Depoimentos → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.default.primary.depoimentos_fetch[].card_depoimentos
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_depoimentos: prismic.ContentRelationshipField<"depoimentos">;
}

/**
 * Primary content in *Depoimentos → Default → Primary*
 */
export interface DepoimentosSliceDefaultPrimary {
  /**
   * Titulo Seção field in *Depoimentos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.default.primary.titulo_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_secao: prismic.KeyTextField;

  /**
   * Depoimentos field in *Depoimentos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.default.primary.depoimentos_fetch[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  depoimentos_fetch: prismic.GroupField<
    Simplify<DepoimentosSliceDefaultPrimaryDepoimentosFetchItem>
  >;
}

/**
 * Default variation for Depoimentos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DepoimentosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Depoimentos*
 */
type DepoimentosSliceVariation = DepoimentosSliceDefault;

/**
 * Depoimentos Shared Slice
 *
 * - **API ID**: `depoimentos`
 * - **Description**: Depoimentos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSlice = prismic.SharedSlice<
  "depoimentos",
  DepoimentosSliceVariation
>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Titulo Seção field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.titulo_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_secao: prismic.KeyTextField;

  /**
   * Descrição Seção field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.descricao_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_secao: prismic.KeyTextField;

  /**
   * Imagem Destaque Seção field in *Form → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.imagem_destaque_secao
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destaque_secao: prismic.ImageField<never>;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Item in *Funcionalidades → Default → Primary → Cadastrar Funcionalidades*
 */
export interface FuncionalidadesSliceDefaultPrimaryCadastrarFuncionalidadesItem {
  /**
   * Icone field in *Funcionalidades → Default → Primary → Cadastrar Funcionalidades*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: funcionalidades.default.primary.cadastrar_funcionalidades[].icone
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icone: prismic.SelectField<"Agenda" | "Analytics" | "Integrações" | "Tempo">;

  /**
   * Titulo Card field in *Funcionalidades → Default → Primary → Cadastrar Funcionalidades*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: funcionalidades.default.primary.cadastrar_funcionalidades[].titulo_card
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_card: prismic.KeyTextField;

  /**
   * Descrição Card field in *Funcionalidades → Default → Primary → Cadastrar Funcionalidades*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: funcionalidades.default.primary.cadastrar_funcionalidades[].descricao_card
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_card: prismic.KeyTextField;
}

/**
 * Primary content in *Funcionalidades → Default → Primary*
 */
export interface FuncionalidadesSliceDefaultPrimary {
  /**
   * Titulo Secao field in *Funcionalidades → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: funcionalidades.default.primary.titulo_secao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_secao: prismic.KeyTextField;

  /**
   * Cadastrar Funcionalidades field in *Funcionalidades → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: funcionalidades.default.primary.cadastrar_funcionalidades[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cadastrar_funcionalidades: prismic.GroupField<
    Simplify<FuncionalidadesSliceDefaultPrimaryCadastrarFuncionalidadesItem>
  >;
}

/**
 * Default variation for Funcionalidades Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FuncionalidadesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FuncionalidadesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Funcionalidades*
 */
type FuncionalidadesSliceVariation = FuncionalidadesSliceDefault;

/**
 * Funcionalidades Shared Slice
 *
 * - **API ID**: `funcionalidades`
 * - **Description**: Funcionalidades
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FuncionalidadesSlice = prismic.SharedSlice<
  "funcionalidades",
  FuncionalidadesSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * TextoHero field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Aqui você pode cadastrar o texto
   * - **API ID Path**: hero_section.default.primary.textohero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textohero: prismic.RichTextField;

  /**
   * DescricaoHero field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Aqui você pode cadastrar o texto
   * - **API ID Path**: hero_section.default.primary.descricaohero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricaohero: prismic.RichTextField;

  /**
   * Link Hero field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.link_hero
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_hero: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * ImagemHero field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.imagemhero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemhero: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Horizontal → Primary*
 */
export interface HeroSectionSliceHorizontalPrimary {
  /**
   * TextoHero field in *HeroSection → Horizontal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Aqui você pode cadastrar o texto
   * - **API ID Path**: hero_section.horizontal.primary.textohero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textohero: prismic.RichTextField;

  /**
   * DescricaoHero field in *HeroSection → Horizontal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Aqui você pode cadastrar o texto
   * - **API ID Path**: hero_section.horizontal.primary.descricaohero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricaohero: prismic.RichTextField;

  /**
   * Link Hero field in *HeroSection → Horizontal → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.horizontal.primary.link_hero
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_hero: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * ImagemHero field in *HeroSection → Horizontal → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.horizontal.primary.imagemhero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemhero: prismic.ImageField<never>;
}

/**
 * Horizontal variation for HeroSection Slice
 *
 * - **API ID**: `horizontal`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceHorizontal = prismic.SharedSliceVariation<
  "horizontal",
  Simplify<HeroSectionSliceHorizontalPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → HozontalSemBotão → Primary*
 */
export interface HeroSectionSliceHozontalSemBotaoPrimary {
  /**
   * TextoHero field in *HeroSection → HozontalSemBotão → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Aqui você pode cadastrar o texto
   * - **API ID Path**: hero_section.hozontalSemBotao.primary.textohero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textohero: prismic.RichTextField;

  /**
   * DescricaoHero field in *HeroSection → HozontalSemBotão → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Aqui você pode cadastrar o texto
   * - **API ID Path**: hero_section.hozontalSemBotao.primary.descricaohero
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricaohero: prismic.RichTextField;

  /**
   * ImagemHero field in *HeroSection → HozontalSemBotão → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.hozontalSemBotao.primary.imagemhero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemhero: prismic.ImageField<never>;
}

/**
 * HozontalSemBotão variation for HeroSection Slice
 *
 * - **API ID**: `hozontalSemBotao`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceHozontalSemBotao = prismic.SharedSliceVariation<
  "hozontalSemBotao",
  Simplify<HeroSectionSliceHozontalSemBotaoPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceHorizontal
  | HeroSectionSliceHozontalSemBotao;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DepoimentosDocument,
      DepoimentosDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavegacaoItem,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ConteudoSlice,
      ConteudoSliceDefaultPrimary,
      ConteudoSliceImagemDireitaPrimary,
      ConteudoSliceVariation,
      ConteudoSliceDefault,
      ConteudoSliceImagemDireita,
      DepoimentosSlice,
      DepoimentosSliceDefaultPrimaryDepoimentosFetchItem,
      DepoimentosSliceDefaultPrimary,
      DepoimentosSliceVariation,
      DepoimentosSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      FuncionalidadesSlice,
      FuncionalidadesSliceDefaultPrimaryCadastrarFuncionalidadesItem,
      FuncionalidadesSliceDefaultPrimary,
      FuncionalidadesSliceVariation,
      FuncionalidadesSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceHorizontalPrimary,
      HeroSectionSliceHozontalSemBotaoPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceHorizontal,
      HeroSectionSliceHozontalSemBotao,
    };
  }
}
