// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  conteudo: dynamic(() => import("./Conteudo")),
  depoimentos: dynamic(() => import("./Depoimentos")),
  form: dynamic(() => import("./Form")),
  funcionalidades: dynamic(() => import("./Funcionalidades")),
  hero_section: dynamic(() => import("./HeroSection")),
};
